# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_type', models.CharField(choices=[('social', 'Social Compliance'), ('environmental', 'Environmental Compliance'), ('quality', 'Quality Compliance'), ('safety', 'Safety Compliance'), ('ethical', 'Ethical Compliance'), ('other', 'Other')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('audit_date', models.DateField()),
                ('audit_by', models.CharField(blank=True, max_length=255)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('corrective_action', 'Corrective Action Required')], default='planned', max_length=50)),
                ('findings', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_records', to='buyers.buyer')),
            ],
            options={
                'verbose_name': 'Compliance Record',
                'verbose_name_plural': 'Compliance Records',
            },
        ),
    ]
