# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancerecord',
            options={'ordering': ['-id'], 'verbose_name': 'ComplianceRecord', 'verbose_name_plural': 'ComplianceRecords'},
        ),
    ]
