# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_currency_id_alter_location_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-id'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencys'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
