# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('merchandising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('subcontractor_name', models.CharField(max_length=255)),
                ('process', models.CharField(choices=[('cutting', 'Cutting'), ('sewing', 'Sewing'), ('washing', 'Washing'), ('embroidery', 'Embroidery'), ('printing', 'Printing'), ('finishing', 'Finishing'), ('packing', 'Packing')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('expected_completion', models.DateField()),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontract_orders', to='merchandising.purchaseorder')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontract_orders', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Subcontract Order',
                'verbose_name_plural': 'Subcontract Orders',
                'unique_together': {('order_number',)},
            },
        ),
        migrations.CreateModel(
            name='SubcontractTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_date', models.DateField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('quantity_passed', models.PositiveIntegerField(default=0)),
                ('quantity_rejected', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subcontract_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='subcontract.subcontractorder')),
            ],
            options={
                'verbose_name': 'Subcontract Tracking',
                'verbose_name_plural': 'Subcontract Tracking',
            },
        ),
    ]
