# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcontract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcontractorder',
            options={'ordering': ['-id'], 'verbose_name': 'SubcontractOrder', 'verbose_name_plural': 'SubcontractOrders'},
        ),
        migrations.AlterModelOptions(
            name='subcontracttracking',
            options={'ordering': ['-id'], 'verbose_name': 'SubcontractTracking', 'verbose_name_plural': 'SubcontractTrackings'},
        ),
    ]
