# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('merchandising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(help_text='Daily capacity in pieces')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.productionline')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='merchandising.purchaseorder')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'unique_together': {('order_number',)},
            },
        ),
        migrations.CreateModel(
            name='InspectionPacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inspected_quantity', models.PositiveIntegerField()),
                ('passed_quantity', models.PositiveIntegerField()),
                ('failed_quantity', models.PositiveIntegerField(default=0)),
                ('packed_quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_packing', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Inspection & Packing',
                'verbose_name_plural': 'Inspection & Packing',
            },
        ),
        migrations.CreateModel(
            name='FloorRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_approved', models.PositiveIntegerField(blank=True, null=True)),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_requisitions', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Floor Requisition',
                'verbose_name_plural': 'Floor Requisitions',
            },
        ),
        migrations.CreateModel(
            name='CuttingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_cut', models.PositiveIntegerField()),
                ('fabric_used', models.DecimalField(decimal_places=2, help_text='Fabric used in yards/meters', max_digits=10)),
                ('waste_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_records', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Cutting Record',
                'verbose_name_plural': 'Cutting Records',
            },
        ),
        migrations.CreateModel(
            name='SewingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('input_quantity', models.PositiveIntegerField()),
                ('output_quantity', models.PositiveIntegerField()),
                ('defect_quantity', models.PositiveIntegerField(default=0)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sewing_records', to='production.productionline')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sewing_records', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Sewing Record',
                'verbose_name_plural': 'Sewing Records',
            },
        ),
    ]
