# Generated by Django 6.0.7 on 2026-08-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_cuttingrecord_id_alter_floorrequisition_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Unit',
                'verbose_name_plural': 'Production Units',
            },
        ),
        migrations.CreateModel(
            name='BottleneckAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottleneck_alerts', to='production.productionline')),
            ],
            options={
                'verbose_name': 'Bottleneck Alert',
                'verbose_name_plural': 'Bottleneck Alerts',
            },
        ),
        migrations.CreateModel(
            name='DefectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('defect_type', models.CharField(blank=True, max_length=100)),
                ('checked_quantity', models.PositiveIntegerField()),
                ('defect_quantity', models.PositiveIntegerField()),
                ('defect_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_logs', to='production.productionline')),
            ],
            options={
                'verbose_name': 'Defect Log',
                'verbose_name_plural': 'Defect Logs',
            },
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='production.productionline')),
            ],
            options={
                'verbose_name': 'Heatmap Data',
                'verbose_name_plural': 'Heatmap Data',
            },
        ),
        migrations.CreateModel(
            name='LineCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_capacity_pcs', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='production.productionline')),
            ],
            options={
                'verbose_name': 'Line Capacity',
                'verbose_name_plural': 'Line Capacities',
            },
        ),
        migrations.CreateModel(
            name='OEELog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('availability_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('performance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quality_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oee_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oee_logs', to='production.productionline')),
            ],
            options={
                'verbose_name': 'OEE Log',
                'verbose_name_plural': 'OEE Logs',
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('output_quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='production.productionline')),
            ],
            options={
                'verbose_name': 'Production Record',
                'verbose_name_plural': 'Production Records',
            },
        ),
        migrations.CreateModel(
            name='ProductionShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='production.productionline')),
            ],
            options={
                'verbose_name': 'Production Shift',
                'verbose_name_plural': 'Production Shifts',
            },
        ),
        migrations.AddField(
            model_name='productionline',
            name='production_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='production.productionunit'),
        ),
    ]
