# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionunit_bottleneckalert_defectlog_heatmapdata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottleneckalert',
            options={'ordering': ['-id'], 'verbose_name': 'BottleneckAlert', 'verbose_name_plural': 'BottleneckAlerts'},
        ),
        migrations.AlterModelOptions(
            name='cuttingrecord',
            options={'ordering': ['-id'], 'verbose_name': 'CuttingRecord', 'verbose_name_plural': 'CuttingRecords'},
        ),
        migrations.AlterModelOptions(
            name='defectlog',
            options={'ordering': ['-id'], 'verbose_name': 'DefectLog', 'verbose_name_plural': 'DefectLogs'},
        ),
        migrations.AlterModelOptions(
            name='floorrequisition',
            options={'ordering': ['-id'], 'verbose_name': 'FloorRequisition', 'verbose_name_plural': 'FloorRequisitions'},
        ),
        migrations.AlterModelOptions(
            name='heatmapdata',
            options={'ordering': ['-id'], 'verbose_name': 'HeatmapData', 'verbose_name_plural': 'HeatmapDatas'},
        ),
        migrations.AlterModelOptions(
            name='inspectionpacking',
            options={'ordering': ['-id'], 'verbose_name': 'InspectionPacking', 'verbose_name_plural': 'InspectionPackings'},
        ),
        migrations.AlterModelOptions(
            name='linecapacity',
            options={'ordering': ['-id'], 'verbose_name': 'LineCapacity', 'verbose_name_plural': 'LineCapacitys'},
        ),
        migrations.AlterModelOptions(
            name='oeelog',
            options={'ordering': ['-id'], 'verbose_name': 'OEELog', 'verbose_name_plural': 'OEELogs'},
        ),
        migrations.AlterModelOptions(
            name='productionline',
            options={'ordering': ['name'], 'verbose_name': 'ProductionLine', 'verbose_name_plural': 'ProductionLines'},
        ),
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'ProductionOrder', 'verbose_name_plural': 'ProductionOrders'},
        ),
        migrations.AlterModelOptions(
            name='productionrecord',
            options={'ordering': ['-id'], 'verbose_name': 'ProductionRecord', 'verbose_name_plural': 'ProductionRecords'},
        ),
        migrations.AlterModelOptions(
            name='productionshift',
            options={'ordering': ['-id'], 'verbose_name': 'ProductionShift', 'verbose_name_plural': 'ProductionShifts'},
        ),
        migrations.AlterModelOptions(
            name='productionunit',
            options={'ordering': ['-id'], 'verbose_name': 'ProductionUnit', 'verbose_name_plural': 'ProductionUnits'},
        ),
        migrations.AlterModelOptions(
            name='sewingrecord',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'SewingRecord', 'verbose_name_plural': 'SewingRecords'},
        ),
    ]
