# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_attendance_id_alter_bonus_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-id'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-id'], 'verbose_name': 'Bonus', 'verbose_name_plural': 'Bonus'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-id'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['-id'], 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-id'], 'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
        migrations.AlterModelOptions(
            name='overtime',
            options={'ordering': ['-id'], 'verbose_name': 'Overtime', 'verbose_name_plural': 'Overtimes'},
        ),
        migrations.AlterModelOptions(
            name='salarysheet',
            options={'ordering': ['-id'], 'verbose_name': 'SalarySheet', 'verbose_name_plural': 'SalarySheets'},
        ),
    ]
