# Generated by Django 6.0.7 on 2026-08-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_alter_buyer_id_alter_buyerportfolio_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ('sequence',), 'verbose_name': 'Buyer', 'verbose_name_plural': 'Buyers'},
        ),
        migrations.AddField(
            model_name='buyer',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
