# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_alter_buyer_options_buyer_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerportfolio',
            options={'ordering': ['-id'], 'verbose_name': 'BuyerPortfolio', 'verbose_name_plural': 'BuyerPortfolios'},
        ),
        migrations.AlterModelOptions(
            name='buyerrating',
            options={'ordering': ['-id'], 'verbose_name': 'BuyerRating', 'verbose_name_plural': 'BuyerRatings'},
        ),
    ]
