# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancerecord',
            options={'ordering': ['-id'], 'verbose_name': 'PerformanceRecord', 'verbose_name_plural': 'PerformanceRecords'},
        ),
    ]
