# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountspayable',
            options={'ordering': ['-id'], 'verbose_name': 'AccountsPayable', 'verbose_name_plural': 'AccountsPayables'},
        ),
        migrations.AlterModelOptions(
            name='accountsreceivable',
            options={'ordering': ['-id'], 'verbose_name': 'AccountsReceivable', 'verbose_name_plural': 'AccountsReceivables'},
        ),
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'ordering': ['-id'], 'verbose_name': 'ChartOfAccount', 'verbose_name_plural': 'ChartOfAccounts'},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ['-id'], 'verbose_name': 'CostCenter', 'verbose_name_plural': 'CostCenters'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-id'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-id'], 'verbose_name': 'JournalEntry', 'verbose_name_plural': 'JournalEntrys'},
        ),
    ]
