# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dashboard_type', models.CharField(choices=[('management', 'Management Dashboard'), ('production', 'Production Dashboard'), ('quality', 'Quality Dashboard'), ('financial', 'Financial Dashboard')], max_length=50)),
                ('config', models.JSONField(default=dict, help_text='Dashboard widget configuration')),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('mis', 'MIS Report'), ('production', 'Production Report'), ('efficiency', 'Efficiency Report'), ('quality', 'Quality Report'), ('financial', 'Financial Report'), ('inventory', 'Inventory Report'), ('hr', 'HR Report'), ('custom', 'Custom Report')], max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='generating', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
