# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-id'], 'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-id'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
