# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('style_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='buyers.buyer')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
                'unique_together': {('style_number',)},
            },
        ),
        migrations.CreateModel(
            name='SMVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smv', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calculated_by', models.CharField(max_length=255)),
                ('calculation_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smv_records', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'SMV Record',
                'verbose_name_plural': 'SMV Records',
            },
        ),
        migrations.CreateModel(
            name='SampleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('fit', 'Fit Sample'), ('pp', 'PP Sample'), ('size_set', 'Size Set'), ('pre_production', 'Pre-Production'), ('photo', 'Photo Sample'), ('shipping', 'Shipping Sample')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('request_date', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_orders', to='buyers.buyer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_orders', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Sample Order',
                'verbose_name_plural': 'Sample Orders',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_monitoring', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Development Monitoring',
                'verbose_name_plural': 'Development Monitoring',
            },
        ),
        migrations.CreateModel(
            name='BuyerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_date', models.DateField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('quoted', 'Quoted'), ('converted', 'Converted to Order'), ('lost', 'Lost')], default='received', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='buyers.buyer')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Buyer Enquiry',
                'verbose_name_plural': 'Buyer Enquiries',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='buyers.buyer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'unique_together': {('po_number',)},
            },
        ),
    ]
