# Generated by Django 5.2.13 on 2026-07-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_alter_buyer_id_alter_buyerportfolio_id_and_more'),
        ('core', '0002_alter_currency_id_alter_location_id_and_more'),
        ('hr', '0003_alter_attendance_id_alter_bonus_id_and_more'),
        ('merchandising', '0001_initial'),
        ('production', '0002_alter_cuttingrecord_id_alter_floorrequisition_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerenquiry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='developmentmonitoring',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sampleorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smvrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='style',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BudgetDemandAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('forecast_quantity', models.PositiveIntegerField()),
                ('booked_quantity', models.PositiveIntegerField(default=0)),
                ('gap_quantity', models.PositiveIntegerField(default=0)),
                ('revenue_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_demand_assessments', to='buyers.buyer')),
            ],
            options={
                'verbose_name': 'Budget Demand Assessment',
                'verbose_name_plural': 'Budget Demand Assessments',
            },
        ),
        migrations.CreateModel(
            name='IeSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('current_pph', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target_pph', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('implemented', 'Implemented'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ie_suggestions', to='production.productionline')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ie_suggestions', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'IE Suggestion',
                'verbose_name_plural': 'IE Suggestions',
            },
        ),
        migrations.CreateModel(
            name='ProcessWiseTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255)),
                ('target_quantity', models.PositiveIntegerField()),
                ('achieved_quantity', models.PositiveIntegerField(default=0)),
                ('variance', models.IntegerField(default=0)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('exceeded', 'Exceeded'), ('on_track', 'On Track'), ('behind', 'Behind')], default='on_track', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process Wise Target',
                'verbose_name_plural': 'Process Wise Targets',
            },
        ),
        migrations.CreateModel(
            name='ProductionDowntime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cause', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('resolved', 'Resolved')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to='production.productionline')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Production Downtime',
                'verbose_name_plural': 'Production Downtimes',
            },
        ),
        migrations.CreateModel(
            name='SkillInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(blank=True, max_length=255)),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('multi_skill', models.BooleanField(default=False)),
                ('last_assessed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_inventories', to='hr.employee')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_inventories', to='production.productionline')),
            ],
            options={
                'verbose_name': 'Skill Inventory',
                'verbose_name_plural': 'Skill Inventories',
            },
        ),
    ]
