# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0004_orderitem_orderstagelog_season_style_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetdemandassessment',
            options={'ordering': ['-id'], 'verbose_name': 'BudgetDemandAssessment', 'verbose_name_plural': 'BudgetDemandAssessments'},
        ),
        migrations.AlterModelOptions(
            name='buyerenquiry',
            options={'ordering': ['-id'], 'verbose_name': 'BuyerEnquiry', 'verbose_name_plural': 'BuyerEnquirys'},
        ),
        migrations.AlterModelOptions(
            name='developmentmonitoring',
            options={'ordering': ['-id'], 'verbose_name': 'DevelopmentMonitoring', 'verbose_name_plural': 'DevelopmentMonitorings'},
        ),
        migrations.AlterModelOptions(
            name='iesuggestion',
            options={'ordering': ['-id'], 'verbose_name': 'IeSuggestion', 'verbose_name_plural': 'IeSuggestions'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id'], 'verbose_name': 'OrderItem', 'verbose_name_plural': 'OrderItems'},
        ),
        migrations.AlterModelOptions(
            name='orderstagelog',
            options={'ordering': ['-id'], 'verbose_name': 'OrderStageLog', 'verbose_name_plural': 'OrderStageLogs'},
        ),
        migrations.AlterModelOptions(
            name='processwisetarget',
            options={'ordering': ['-id'], 'verbose_name': 'ProcessWiseTarget', 'verbose_name_plural': 'ProcessWiseTargets'},
        ),
        migrations.AlterModelOptions(
            name='productiondowntime',
            options={'ordering': ['-id'], 'verbose_name': 'ProductionDowntime', 'verbose_name_plural': 'ProductionDowntimes'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-id'], 'verbose_name': 'PurchaseOrder', 'verbose_name_plural': 'PurchaseOrders'},
        ),
        migrations.AlterModelOptions(
            name='sampleorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'SampleOrder', 'verbose_name_plural': 'SampleOrders'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-id'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='skillinventory',
            options={'ordering': ['-id'], 'verbose_name': 'SkillInventory', 'verbose_name_plural': 'SkillInventorys'},
        ),
        migrations.AlterModelOptions(
            name='smvrecord',
            options={'ordering': ['-id'], 'verbose_name': 'SMVRecord', 'verbose_name_plural': 'SMVRecords'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['-id'], 'verbose_name': 'Style', 'verbose_name_plural': 'Styles'},
        ),
    ]
