# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('composition', models.CharField(blank=True, max_length=255)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='meters', max_length=20)),
                ('threshold_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fabric',
                'verbose_name_plural': 'Fabrics',
            },
        ),
        migrations.CreateModel(
            name='ShadeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade_name', models.CharField(max_length=100)),
                ('shade_code', models.CharField(max_length=50)),
                ('approved_by', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shade_approvals', to='inventory.fabric')),
            ],
            options={
                'verbose_name': 'Shade Approval',
                'verbose_name_plural': 'Shade Approvals',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('fabric', 'Fabric'), ('accessory', 'Accessory'), ('trim', 'Trim')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('transfer', 'Transfer'), ('return', 'Return to Supplier'), ('waste', 'Waste')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='inventory.warehouse')),
                ('to_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
            },
        ),
        migrations.CreateModel(
            name='PhysicalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_inventories', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Physical Inventory',
                'verbose_name_plural': 'Physical Inventories',
            },
        ),
        migrations.AddField(
            model_name='fabric',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('threshold_quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trims', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Trim',
                'verbose_name_plural': 'Trims',
                'unique_together': {('code',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='fabric',
            unique_together={('code',)},
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('threshold_quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'unique_together': {('code',)},
            },
        ),
    ]
