# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['-id'], 'verbose_name': 'Accessory', 'verbose_name_plural': 'Accessorys'},
        ),
        migrations.AlterModelOptions(
            name='fabric',
            options={'ordering': ['-id'], 'verbose_name': 'Fabric', 'verbose_name_plural': 'Fabrics'},
        ),
        migrations.AlterModelOptions(
            name='physicalinventory',
            options={'ordering': ['-id'], 'verbose_name': 'PhysicalInventory', 'verbose_name_plural': 'PhysicalInventorys'},
        ),
        migrations.AlterModelOptions(
            name='shadeapproval',
            options={'ordering': ['-id'], 'verbose_name': 'ShadeApproval', 'verbose_name_plural': 'ShadeApprovals'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-id'], 'verbose_name': 'StockMovement', 'verbose_name_plural': 'StockMovements'},
        ),
        migrations.AlterModelOptions(
            name='trim',
            options={'ordering': ['-id'], 'verbose_name': 'Trim', 'verbose_name_plural': 'Trims'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-id'], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
    ]
