# Generated by Django 6.0.7 on 2026-08-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuthCallbackUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], max_length=50, unique=True)),
                ('callback_url', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': 'Social Auth Callback URL',
                'verbose_name_plural': 'Social Auth Callback URLs',
            },
        ),
    ]
