# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-id'], 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterModelOptions(
            name='socialauthcallbackurl',
            options={'ordering': ['-id'], 'verbose_name': 'SocialAuthCallbackUrl', 'verbose_name_plural': 'SocialAuthCallbackUrls'},
        ),
    ]
