"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=True, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
# A hardcoded insecure fallback is only acceptable while DEBUG=True; in
# production a missing DJANGO_SECRET_KEY must fail loudly instead of silently
# running with a publicly-known key (session/OTP/JWT forgery risk).
if DEBUG:
    SECRET_KEY = config(
        "DJANGO_SECRET_KEY",
        default="django-insecure-8t2p2rgxfg!2x0%1d6(a@k2lc==5!wlnv%vfucqc!d79@f8nim",
    )
else:
    SECRET_KEY = config("DJANGO_SECRET_KEY", default="")
    if not SECRET_KEY:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set via environment when DEBUG=False."
        )

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,testserver" if DEBUG else "localhost",
    cast=Csv(),
)


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'channels',
    'corsheaders',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django_filters',
    'crispy_forms',
    'authentication',
    'core',
    'buyers',
    'merchandising',
    'ie_planning',
    'production',
    'inventory',
    'procurement',
    'quality',
    'subcontract',
    'accounts',
    'commercial',
    'crm',
    'hr',
    'fixed_assets',
    'tna',
    'costing',
    'orders',
    'compliance',
    'reporting',
    'performance',
    'planning',
    'scheduling',
    'rbac',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

INSTALLED_APPS += [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    "unfold.contrib.hijack",  # optional, if django-hijack package is used
    "config.apps.TexonAdminConfig",  # required - custom AdminSite (unfold)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Uses Supabase Postgres when SUPABASE_DB_HOST is set (see .env);
# otherwise falls back to local SQLite for development.

if config("SUPABASE_DB_HOST", default=""):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('SUPABASE_DB_NAME', default='postgres'),
            'USER': config('SUPABASE_DB_USER', default='postgres'),
            'PASSWORD': config('SUPABASE_DB_PASSWORD', default=''),
            'HOST': config('SUPABASE_DB_HOST'),
            'PORT': config('SUPABASE_DB_PORT', default='5432', cast=int),
            'CONN_MAX_AGE': 60,
            'OPTIONS': {
                # Supabase uses a connection pooler on port 6543 that requires
                # disabling prepared statements; harmless on direct connections.
                'sslmode': config('SUPABASE_DB_SSLMODE', default='require'),
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ("en", _("English")),
    ("bn", _("Bengali")),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# django-crispy-forms - Unfold template pack
# https://django-crispy-forms.readthedocs.io/
CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap5", "unfold_crispy")
CRISPY_TEMPLATE_PACK = "unfold_crispy"

# django-unfold configuration
# https://unfoldadmin.com/docs/configuration/


def _changelist_tab(link, query=""):
    return lambda request: str(link) + query


UNFOLD = {
    "SITE_TITLE": "Texon RMG ERP",
    "SITE_HEADER": "Texon",
    "SITE_SUBHEADER": "RMG ERP Backoffice",
    "SITE_VERSION": "1.0.0",
    "SITE_SYMBOL": "factory",
    "SITE_URL": "/admin/",
    # Site dropdown - switch between multiple admin sites
    "SITE_DROPDOWN": [
        {"title": _("Backoffice"), "link": reverse_lazy("admin:index")},
        {"title": _("Operations"), "link": reverse_lazy("operations:index")},
    ],
    # Command palette
    "COMMAND": {
        "search_models": True,
        "show_history": True,
        "search_callback": "core.admin_search.search_callback",
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": True,
    # Multi-language switcher
    "SHOW_LANGUAGES": True,
    "LANGUAGE_FLAGS": {
        "en": "🇬🇧",
        "bn": "🇧🇩",
    },
    "LANGUAGES": {
        "navigation": [
            {"title": _("English"), "name_local": "English", "link": "/", "code": "en"},
            {"title": _("Bengali"), "name_local": "বাংলা", "link": "/", "code": "bn"},
        ],
    },
    "ENVIRONMENT": "development" if DEBUG else "production",
    "ENVIRONMENT_TITLE_PREFIX": "DEV",
    # Dashboard - custom index page (core/dashboard.py)
    "DASHBOARD_CALLBACK": "core.dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "oklch(98.4% .018 155.826)",
            "100": "oklch(96.8% .045 155.086)",
            "200": "oklch(93.5% .089 154.878)",
            "300": "oklch(88.7% .132 154.843)",
            "400": "oklch(81.4% .173 155.384)",
            "500": "oklch(73.6% .203 155.908)",
            "600": "oklch(64.2% .215 156.478)",
            "700": "oklch(52.4% .187 156.943)",
            "800": "oklch(42.7% .156 157.19)",
            "900": "oklch(37.9% .124 157.218)",
            "950": "oklch(25.2% .087 157.364)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Operations"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Orders"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:orders_order_changelist"),
                    },
                    {
                        "title": _("Buyers"),
                        "icon": "handshake",
                        "link": reverse_lazy("admin:buyers_buyer_changelist"),
                    },
                ],
            },
            {
                "title": _("People"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:authentication_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Pages"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Reports"),
                        "icon": "monitoring",
                        "link": reverse_lazy("admin:reports"),
                    },
                    {
                        "title": _("Crispy Form Demo"),
                        "icon": "dynamic_form",
                        "link": reverse_lazy("admin:crispy-demo"),
                    },
                ],
            },
        ],
    },
    # Changelist tabs - quick filters on the Order changelist
    "TABS": [
        {
            "models": ["orders.order"],
            "items": [
                {
                    "title": _("All orders"),
                    "link": reverse_lazy("admin:orders_order_changelist"),
                },
                {
                    "title": _("Pending"),
                    "link": _changelist_tab(reverse_lazy("admin:orders_order_changelist"), "?status__exact=pending"),
                },
                {
                    "title": _("Confirmed"),
                    "link": _changelist_tab(reverse_lazy("admin:orders_order_changelist"), "?status__exact=confirmed"),
                },
                {
                    "title": _("In production"),
                    "link": _changelist_tab(reverse_lazy("admin:orders_order_changelist"), "?status__exact=in_production"),
                },
                {
                    "title": _("Shipped"),
                    "link": _changelist_tab(reverse_lazy("admin:orders_order_changelist"), "?status__exact=shipped"),
                },
                {
                    "title": _("Delivered"),
                    "link": _changelist_tab(reverse_lazy("admin:orders_order_changelist"), "?status__exact=delivered"),
                },
            ],
        },
    ],
    "ACCOUNT": {
        "navigation": [
            {"title": _("Profile"), "link": reverse_lazy("admin:index")},
            {
                "title": _("Logout"),
                "link": reverse_lazy("admin:logout"),
            },
        ],
    },
    "LOGIN": {
        "redirect_after": "/admin/",
    },
    "STYLES": [],
    "SCRIPTS": [],
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

AUTH_USER_MODEL = "authentication.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardResultsPagination",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "auth_login": "30/hour",
    },
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "COERCE_DECIMAL_TO_STRING": True,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Texon RMG ERP API",
    "DESCRIPTION": "Enterprise Ready-Made Garments ERP System. "
    "Comprehensive API for managing buyers, merchandising, production, "
    "inventory, HR, accounts, compliance, and all factory operations.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/v1/",
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    "COMPONENT_NO_READ_ONLY_REQUIRED": True,
    "POSTPROCESSING_HOOKS": [],
    "ENUM_NAME_OVERRIDES": {},
    "TOS": None,
    "CONTACT": {"email": "admin@texon.com"},
    "LICENSE": {"name": "MIT"},
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=config("JWT_ACCESS_EXPIRY", default=15, cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=config("JWT_REFRESH_EXPIRY", default=7, cast=int)),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# Never allow all origins with credentials in production; set explicitly via env.
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=False, cast=bool)
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="http://localhost:3000,http://127.0.0.1:3000", cast=Csv())
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "x-csrftoken",
    "x-requested-with",
]

EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@texon.com")

AI_LLM_PROVIDER = config("AI_LLM_PROVIDER", default="lm_studio")
AI_LLM_CONFIG = {
    "lm_studio": {
        "base_url": config("LM_STUDIO_BASE_URL", default="http://localhost:1234/v1"),
        "model": config("LM_STUDIO_MODEL", default="local-model"),
        "api_key": config("LM_STUDIO_API_KEY", default="not-needed"),
        "temperature": config("AI_TEMPERATURE", default=0.1, cast=float),
        "max_tokens": config("AI_MAX_TOKENS", default=4096, cast=int),
    },
    "openai": {
        "base_url": config("OPENAI_BASE_URL", default="https://api.openai.com/v1"),
        "model": config("OPENAI_MODEL", default="gpt-4o-mini"),
        "api_key": config("OPENAI_API_KEY", default=""),
        "temperature": config("AI_TEMPERATURE", default=0.1, cast=float),
        "max_tokens": config("AI_MAX_TOKENS", default=4096, cast=int),
    },
    "deepseek": {
        "base_url": config("DEEPSEEK_BASE_URL", default="https://api.deepseek.com/v1"),
        "model": config("DEEPSEEK_MODEL", default="deepseek-chat"),
        "api_key": config("DEEPSEEK_API_KEY", default=""),
        "temperature": config("AI_TEMPERATURE", default=0.0, cast=float),
        "max_tokens": config("AI_MAX_TOKENS", default=4096, cast=int),
    },
}

# dj-rest-auth and allauth settings
SITE_ID = 1

REST_USE_JWT = True

ACCOUNT_USER_MODEL = 'authentication.User'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# 'none' is only acceptable in development. Production must verify emails
# (override via the ACCOUNT_EMAIL_VERIFICATION env var if needed).
ACCOUNT_EMAIL_VERIFICATION = config(
    "ACCOUNT_EMAIL_VERIFICATION",
    default="none" if DEBUG else "mandatory",
)

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'jwt-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'jwt-refresh-token',
    'TOKEN_MODEL': None,
    'USER_DETAILS_SERIALIZER': 'authentication.serializers.UserDetailsSerializer',
}

# Allowlisted redirect targets for OAuth callback_url overrides. The frontend
# may request a specific callback_url, but only host:port entries listed here
# are accepted (open-redirect / authorization-code interception defence).
# Add your production frontend origin(s) via the SOCIAL_CALLBACK_ALLOWLIST env
# var, e.g. "app.texon.com:443,localhost:3000".
SOCIAL_CALLBACK_ALLOWLIST = config(
    "SOCIAL_CALLBACK_ALLOWLIST",
    default="localhost:3000,127.0.0.1:3000",
    cast=Csv(),
)

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    },
    'github': {
        'SCOPE': [
            'user',
            'read:user',
            'user:email',
        ],
    }
}
