"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import warnings

from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Secure by default: DEBUG pages disclose the full URL map and settings.
# Local dev must opt in via DJANGO_DEBUG=True in backend/.env.
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
# A hardcoded insecure fallback is only acceptable while DEBUG=True; in
# production a missing DJANGO_SECRET_KEY must fail loudly instead of silently
# running with a publicly-known key (session/OTP/JWT forgery risk).
if DEBUG:
    SECRET_KEY = config(
        "DJANGO_SECRET_KEY",
        default="django-insecure-8t2p2rgxfg!2x0%1d6(a@k2lc==5!wlnv%vfucqc!d79@f8nim",
    )
else:
    SECRET_KEY = config("DJANGO_SECRET_KEY", default="")
    if not SECRET_KEY:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set via environment when DEBUG=False."
        )

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,testserver" if DEBUG else "localhost",
    cast=Csv(),
)

# ---------------------------------------------------------------------------
# Vercel deployment
# ---------------------------------------------------------------------------
# Vercel injects VERCEL=1 into its serverless runtime. When running there we
# additionally trust the *.vercel.app preview/production domains and the
# platform's TLS-terminating proxy.
IS_VERCEL = config("VERCEL", default=False, cast=bool)

if IS_VERCEL:
    ALLOWED_HOSTS += [".vercel.app"]

if not DEBUG:
    # Trust the X-Forwarded-Proto header from Vercel's edge proxy so Django
    # knows requests arrived over HTTPS (required for secure cookies/CSRF).
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Extra origins trusted for POSTing (admin login, OAuth callbacks) when the
# site is served behind a proxy/domain other than the request host.
CSRF_TRUSTED_ORIGINS = [
    origin for origin in config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv()) if origin
]


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'channels',
    'corsheaders',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django_filters',
    'crispy_forms',
    'authentication',
    'core',
    'buyers',
    'merchandising',
    'ie_planning',
    'production',
    'inventory',
    'procurement',
    'quality',
    'subcontract',
    'accounts',
    'commercial',
    'crm',
    'hr',
    'fixed_assets',
    'tna',
    'costing',
    'orders',
    'compliance',
    'reporting',
    'performance',
    'planning',
    'scheduling',
    'rbac',
    'ai',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

INSTALLED_APPS += [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    "unfold.contrib.hijack",  # optional, if django-hijack package is used
    "config.apps.TexonAdminConfig",  # required - custom AdminSite (unfold)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Uses Supabase Postgres when SUPABASE_DB_HOST is set (see .env);
# otherwise falls back to local SQLite for development.

if config("SUPABASE_DB_HOST", default=""):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('SUPABASE_DB_NAME', default='postgres'),
            'USER': config('SUPABASE_DB_USER', default='postgres'),
            'PASSWORD': config('SUPABASE_DB_PASSWORD', default=''),
            'HOST': config('SUPABASE_DB_HOST'),
            'PORT': config('SUPABASE_DB_PORT', default='5432', cast=int),
            'CONN_MAX_AGE': 60,
            'OPTIONS': {
                # Supabase uses a connection pooler on port 6543 that requires
                # disabling prepared statements; harmless on direct connections.
                'sslmode': config('SUPABASE_DB_SSLMODE', default='require'),
                # Disable server-side prepared statements when using a
                # Supavisor/pgbouncer pooler which doesn't support them.
                # Can be overridden via SUPABASE_DB_OPTIONS in .env
                'options': config('SUPABASE_DB_OPTIONS', default='-c prepare_threshold=0'),
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # OWASP A07: require a 12+ character passphrase (was Django's default 8).
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ("en", "English"),
    ("bn", "Bengali"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# django-crispy-forms - Unfold template pack
# https://django-crispy-forms.readthedocs.io/
CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap5", "unfold_crispy")
CRISPY_TEMPLATE_PACK = "unfold_crispy"

# django-unfold configuration
# https://unfoldadmin.com/docs/configuration/


def _changelist_tab(link, query=""):
    return lambda request: str(link) + query


UNFOLD = {
    "SITE_TITLE": "Texon RMG ERP",
    "SITE_HEADER": "Texon",
    "SITE_SUBHEADER": "RMG ERP Backoffice",
    "SITE_VERSION": "1.0.0",
    "SITE_SYMBOL": "factory",
    "SITE_URL": "/admin/",
    # Site dropdown - switch between multiple admin sites
    "SITE_DROPDOWN": [
        {"title": "Backoffice", "link": "/admin/"},
        {"title": "Operations", "link": "/operations/"},
    ],
    # Command palette
    "COMMAND": {
        "search_models": True,
        "show_history": True,
        "search_callback": "core.admin_search.search_callback",
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": True,
    # Multi-language switcher
    "SHOW_LANGUAGES": True,
    "LANGUAGE_FLAGS": {
        "en": "🇬🇧",
        "bn": "🇧🇩",
    },
    "LANGUAGES": {
        "navigation": [
            {"title": "English", "name_local": "English", "link": "/", "code": "en"},
            {"title": "Bengali", "name_local": "বাংলা", "link": "/", "code": "bn"},
        ],
    },
    "ENVIRONMENT": "development" if DEBUG else "production",
    "ENVIRONMENT_TITLE_PREFIX": "DEV",
    # Dashboard - custom index page (core/dashboard.py)
    "DASHBOARD_CALLBACK": "core.dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "oklch(98.4% .018 155.826)",
            "100": "oklch(96.8% .045 155.086)",
            "200": "oklch(93.5% .089 154.878)",
            "300": "oklch(88.7% .132 154.843)",
            "400": "oklch(81.4% .173 155.384)",
            "500": "oklch(73.6% .203 155.908)",
            "600": "oklch(64.2% .215 156.478)",
            "700": "oklch(52.4% .187 156.943)",
            "800": "oklch(42.7% .156 157.19)",
            "900": "oklch(37.9% .124 157.218)",
            "950": "oklch(25.2% .087 157.364)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Operations",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Orders",
                        "icon": "receipt_long",
                        "link": "/admin/orders/order/",
                    },
                    {
                        "title": "Buyers",
                        "icon": "handshake",
                        "link": "/admin/buyers/buyer/",
                    },
                ],
            },
            {
                "title": "People",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": "/admin/authentication/user/",
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
            {
                "title": "Pages",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Reports",
                        "icon": "monitoring",
                        "link": "/admin/reports/",
                    },
                    {
                        "title": "Crispy Form Demo",
                        "icon": "dynamic_form",
                        "link": "/admin/crispy-demo/",
                    },
                ],
            },
        ],
    },
    # Changelist tabs - quick filters on the Order changelist
    "TABS": [
        {
            "models": ["orders.order"],
            "items": [
                {
                    "title": "All orders",
                    "link": "/admin/orders/order/",
                },
                {
                    "title": "Pending",
                    "link": _changelist_tab("/admin/orders/order/", "?status__exact=pending"),
                },
                {
                    "title": "Confirmed",
                    "link": _changelist_tab("/admin/orders/order/", "?status__exact=confirmed"),
                },
                {
                    "title": "In production",
                    "link": _changelist_tab("/admin/orders/order/", "?status__exact=in_production"),
                },
                {
                    "title": "Shipped",
                    "link": _changelist_tab("/admin/orders/order/", "?status__exact=shipped"),
                },
                {
                    "title": "Delivered",
                    "link": _changelist_tab("/admin/orders/order/", "?status__exact=delivered"),
                },
            ],
        },
    ],
    "ACCOUNT": {
        "navigation": [
            {"title": "Profile", "link": "/admin/"},
            {
                "title": "Logout",
                "link": "/admin/logout/",
            },
        ],
    },
    "LOGIN": {
        "redirect_after": "/admin/",
    },
    "STYLES": [],
    "SCRIPTS": [],
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Static files settings for deployment (WhiteNoise)
# `collectstatic` will place files into `STATIC_ROOT` during build.
# Lambda's deployment bundle (/var/task) is read-only, so on Vercel we
# collect static files into the writable /tmp filesystem instead (see
# api/index.py, which runs collectstatic on first boot).
STATIC_ROOT = Path('/tmp/staticfiles') if IS_VERCEL else BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Use WhiteNoise's compressed manifest storage for cache-friendly assets.
# NOTE: the manifest variant raises at boot if `collectstatic` hasn't run.
# On ephemeral serverless platforms (Vercel) we therefore use the non-manifest
# variant so a missing manifest never breaks cold starts.
STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedStaticFilesStorage'
    if IS_VERCEL
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

AUTH_USER_MODEL = "authentication.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardResultsPagination",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "auth_login": "30/hour",
    },
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "COERCE_DECIMAL_TO_STRING": True,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Texon RMG ERP API",
    "DESCRIPTION": "Enterprise Ready-Made Garments ERP System. "
    "Comprehensive API for managing buyers, merchandising, production, "
    "inventory, HR, accounts, compliance, and all factory operations.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/v1/",
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    "COMPONENT_NO_READ_ONLY_REQUIRED": True,
    "POSTPROCESSING_HOOKS": [],
    "ENUM_NAME_OVERRIDES": {},
    "TOS": None,
    "CONTACT": {"email": "admin@texon.com"},
    "LICENSE": {"name": "MIT"},
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=config("JWT_ACCESS_EXPIRY", default=15, cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=config("JWT_REFRESH_EXPIRY", default=7, cast=int)),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# Never allow all origins with credentials in production; set explicitly via env.
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=False, cast=bool)
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="http://localhost:3000,http://127.0.0.1:3000", cast=Csv())
CORS_ALLOW_CREDENTIALS = True

# Guardrail (OWASP A05): reflecting any Origin together with credentials lets
# malicious sites read authenticated responses from a victim's browser.
if CORS_ALLOW_ALL_ORIGINS and not DEBUG:
    raise ImproperlyConfigured(
        "CORS_ALLOW_ALL_ORIGINS=True combined with CORS_ALLOW_CREDENTIALS=True "
        "is an exploitable configuration and is refused while DEBUG=False. "
        "Remove the env var and whitelist origins in CORS_ALLOWED_ORIGINS instead."
    )
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "x-csrftoken",
    "x-requested-with",
]

EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@texon.com")

AI_LLM_PROVIDER = config("AI_LLM_PROVIDER", default="openrouter")
AI_LLM_CONFIG = {
    "openrouter": {
        "base_url": config("OPENROUTER_BASE_URL", default="https://openrouter.ai/api/v1"),
        "model": config("OPENROUTER_MODEL", default="openai/gpt-4o-mini"),
        "api_key": config("OPEN_ROUTER_API_KEY", default="") or config("OPENROUTER_API_KEY", default=""),
    },
    "lm_studio": {
        "base_url": config("LM_STUDIO_BASE_URL", default="http://localhost:1234/v1"),
        "model": config("LM_STUDIO_MODEL", default="local-model"),
        "api_key": config("LM_STUDIO_API_KEY", default="not-needed"),
        "temperature": config("AI_TEMPERATURE", default=0.1, cast=float),
        "max_tokens": config("AI_MAX_TOKENS", default=4096, cast=int),
    },
    "openai": {
        "base_url": config("OPENAI_BASE_URL", default="https://api.openai.com/v1"),
        "model": config("OPENAI_MODEL", default="gpt-4o-mini"),
        "api_key": config("OPENAI_API_KEY", default=""),
        "temperature": config("AI_TEMPERATURE", default=0.1, cast=float),
        "max_tokens": config("AI_MAX_TOKENS", default=4096, cast=int),
    },
    "deepseek": {
        "base_url": config("DEEPSEEK_BASE_URL", default="https://api.deepseek.com/v1"),
        "model": config("DEEPSEEK_MODEL", default="deepseek-chat"),
        "api_key": config("DEEPSEEK_API_KEY", default=""),
        "temperature": config("AI_TEMPERATURE", default=0.0, cast=float),
        "max_tokens": config("AI_MAX_TOKENS", default=4096, cast=int),
    },
}

# dj-rest-auth and allauth settings
SITE_ID = 1

REST_USE_JWT = True

ACCOUNT_USER_MODEL = 'authentication.User'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# 'none' is only acceptable in development. Production must verify emails
# (override via the ACCOUNT_EMAIL_VERIFICATION env var if needed).
ACCOUNT_EMAIL_VERIFICATION = config(
    "ACCOUNT_EMAIL_VERIFICATION",
    default="none" if DEBUG else "mandatory",
)

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'jwt-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'jwt-refresh-token',
    # OWASP A02/A05: JWT cookies are HttpOnly, Secure (when not DEBUG) and
    # SameSite=Lax so they are never readable by JS and never sent cross-site.
    'JWT_AUTH_SECURE': not DEBUG,
    'JWT_AUTH_HTTPONLY': True,
    'JWT_AUTH_SAMESITE': 'Lax',
    'TOKEN_MODEL': None,
    'USER_DETAILS_SERIALIZER': 'authentication.serializers.UserDetailsSerializer',
    'REGISTER_SERIALIZER': 'authentication.serializers.RegisterSerializer',
}

# Allowlisted redirect targets for OAuth callback_url overrides. The frontend
# may request a specific callback_url, but only host:port entries listed here
# are accepted (open-redirect / authorization-code interception defence).
# Add your production frontend origin(s) via the SOCIAL_CALLBACK_ALLOWLIST env
# var, e.g. "app.texon.com:443,localhost:3000".
SOCIAL_CALLBACK_ALLOWLIST = config(
    "SOCIAL_CALLBACK_ALLOWLIST",
    default="localhost:3000,127.0.0.1:3000",
    cast=Csv(),
)

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    },
    'github': {
        'SCOPE': [
            'user',
            'read:user',
            'user:email',
        ],
    }
}


# ---------------------------------------------------------------------------
# OWASP Top 10 hardening
# ---------------------------------------------------------------------------
# Transport security & browser hardening headers (A02, A05).
# Active only when DEBUG=False so local HTTP development keeps working.
# Individual flags can be overridden via environment variables.
if not DEBUG:
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"

# Cookie hardening (A02/A07): sessions and CSRF cookies are HttpOnly,
# SameSite=Lax, and Secure in production.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Keep CSRF cookie readable by JS only if a SPA needs the X-CSRFToken
    # header; JWT APIs typically don't. Flip to True via env if required.
    if config("CSRF_COOKIE_HTTPONLY", default=True, cast=bool):
        CSRF_COOKIE_HTTPONLY = True

# Content Security Policy (A03/A05) - Django 6 native support.
# Deployed in REPORT-ONLY mode first so any violation is logged by the browser
# without breaking the Unfold admin; flip to SECURE_CSP once no violations are
# reported (env: CSP_ENFORCE=1).
_CSP_DIRECTIVES = {
    "default-src": ("'self'",),
    # Unfold admin templates rely on inline style/script attributes.
    "script-src": ("'self'", "'unsafe-inline'"),
    "style-src": ("'self'", "'unsafe-inline'"),
    "img-src": ("'self'", "data:", "https:"),
    "font-src": ("'self'",),
    "connect-src": ("'self'",),
    "frame-ancestors": ("'none'",),
    "base-uri": ("'self'",),
    "form-action": ("'self'",),
    "object-src": ("'none'",),
}
if not DEBUG and config("CSP_ENFORCE", default=False, cast=bool):
    SECURE_CSP = _CSP_DIRECTIVES
else:
    SECURE_CSP_REPORT_ONLY = _CSP_DIRECTIVES

# Security logging & monitoring (A09). Auth lifecycle events are emitted by
# core/security_logging.py signal receivers into the "texon.security" logger;
# django.request captures 4xx/5xx, django.security catches suspicious ops.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        # Ring buffer consumed by the admin panel "Logs" page
        # (core/admin_pages.py LogsPage). Mirrors everything that goes to the
        # console so staff can inspect recent logs without platform access.
        "memory": {
            "class": "core.log_buffer.MemoryLogHandler",
            "capacity": 2000,
            "level": "DEBUG",
        },
    },
    "root": {"handlers": ["console", "memory"], "level": "WARNING"},
    "loggers": {
        "django.request": {
            "handlers": ["console", "memory"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console", "memory"],
            "level": "WARNING",
            "propagate": False,
        },
        "texon.security": {
            "handlers": ["console", "memory"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Fail loudly on insecure production configuration (A05). Registered as a
# Django system check in core/apps.py - visible via `manage.py check` and at
# boot on Vercel.
if not DEBUG and "*" in ALLOWED_HOSTS:
    warnings.warn(
        "ALLOWED_HOSTS contains '*': host-header spoofing and cache poisoning "
        "become possible. List your real domains instead.",
        stacklevel=0,
    )
if not DEBUG and CORS_ALLOW_ALL_ORIGINS:
    warnings.warn(
        "CORS_ALLOW_ALL_ORIGINS=True with credentials enabled lets any site "
        "make authenticated cross-origin calls. Set explicit origins in "
        "CORS_ALLOWED_ORIGINS.",
        stacklevel=0,
    )
