# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('core', '0001_initial'),
        ('merchandising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_date', models.DateField()),
                ('fabric_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accessory_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trim_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commercial_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('revised', 'Revised')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheets', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Cost Sheet',
                'verbose_name_plural': 'Cost Sheets',
            },
        ),
        migrations.CreateModel(
            name='PreCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_date', models.DateField()),
                ('estimated_fabric_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_accessory_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_trim_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_overhead', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('revised', 'Revised')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_costings', to='buyers.buyer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_costings', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Pre Costing',
                'verbose_name_plural': 'Pre Costings',
            },
        ),
    ]
