# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costsheet',
            options={'ordering': ['-id'], 'verbose_name': 'CostSheet', 'verbose_name_plural': 'CostSheets'},
        ),
        migrations.AlterModelOptions(
            name='precosting',
            options={'ordering': ['-id'], 'verbose_name': 'PreCosting', 'verbose_name_plural': 'PreCostings'},
        ),
    ]
