# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['-id'], 'verbose_name': 'AssetCategory', 'verbose_name_plural': 'AssetCategorys'},
        ),
        migrations.AlterModelOptions(
            name='depreciationschedule',
            options={'ordering': ['-id'], 'verbose_name': 'DepreciationSchedule', 'verbose_name_plural': 'DepreciationSchedules'},
        ),
        migrations.AlterModelOptions(
            name='fixedasset',
            options={'ordering': ['-id'], 'verbose_name': 'FixedAsset', 'verbose_name_plural': 'FixedAssets'},
        ),
    ]
