# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('core', '0001_initial'),
        ('merchandising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('meeting', 'Meeting'), ('site_visit', 'Site Visit'), ('video_call', 'Video Call'), ('other', 'Other')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('communication_date', models.DateTimeField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending_follow_up', 'Pending Follow-up'), ('closed', 'Closed')], default='completed', max_length=50)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='buyers.buyer')),
            ],
            options={
                'verbose_name': 'Buyer Communication',
                'verbose_name_plural': 'Buyer Communications',
            },
        ),
        migrations.CreateModel(
            name='BuyerProfitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_records', to='buyers.buyer')),
            ],
            options={
                'verbose_name': 'Buyer Profitability',
                'verbose_name_plural': 'Buyer Profitability',
            },
        ),
        migrations.CreateModel(
            name='OrderAmendmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_date', models.DateField()),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField()),
                ('amended_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='merchandising.purchaseorder')),
            ],
            options={
                'verbose_name': 'Order Amendment History',
                'verbose_name_plural': 'Order Amendment Histories',
            },
        ),
    ]
