# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyercommunication',
            options={'ordering': ['-id'], 'verbose_name': 'BuyerCommunication', 'verbose_name_plural': 'BuyerCommunications'},
        ),
        migrations.AlterModelOptions(
            name='buyerprofitability',
            options={'ordering': ['-id'], 'verbose_name': 'BuyerProfitability', 'verbose_name_plural': 'BuyerProfitabilitys'},
        ),
        migrations.AlterModelOptions(
            name='orderamendmenthistory',
            options={'ordering': ['-id'], 'verbose_name': 'OrderAmendmentHistory', 'verbose_name_plural': 'OrderAmendmentHistorys'},
        ),
    ]
