# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Defect Category',
                'verbose_name_plural': 'Defect Categories',
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='EndLineQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('checked_quantity', models.PositiveIntegerField()),
                ('passed_quantity', models.PositiveIntegerField()),
                ('failed_quantity', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('rework', 'Rework')], default='pass', max_length=50)),
                ('checked_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.defectcategory')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endline_qc_records', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'End Line QC',
                'verbose_name_plural': 'End Line QC',
            },
        ),
        migrations.CreateModel(
            name='FabricInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_received_from', models.CharField(max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('inspection_date', models.DateField()),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inspected_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('passed_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('conditional', 'Conditional Pass')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('inspected_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.defectcategory')),
            ],
            options={
                'verbose_name': 'Fabric Inspection',
                'verbose_name_plural': 'Fabric Inspections',
            },
        ),
        migrations.CreateModel(
            name='FinalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspected_quantity', models.PositiveIntegerField()),
                ('passed_quantity', models.PositiveIntegerField()),
                ('failed_quantity', models.PositiveIntegerField(default=0)),
                ('aql_level', models.CharField(blank=True, max_length=10)),
                ('critical_defects', models.PositiveIntegerField(default=0)),
                ('major_defects', models.PositiveIntegerField(default=0)),
                ('minor_defects', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass')], default='pass', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('inspected_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_inspections', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Final Inspection',
                'verbose_name_plural': 'Final Inspections',
            },
        ),
        migrations.CreateModel(
            name='InlineQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_line', models.CharField(max_length=100)),
                ('check_date', models.DateField()),
                ('checked_quantity', models.PositiveIntegerField()),
                ('defect_quantity', models.PositiveIntegerField(default=0)),
                ('defect_description', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('rework', 'Rework')], default='pass', max_length=50)),
                ('checked_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.defectcategory')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_qc_records', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Inline QC',
                'verbose_name_plural': 'Inline QC',
            },
        ),
        migrations.CreateModel(
            name='RejectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('stage', models.CharField(choices=[('cutting', 'Cutting'), ('sewing', 'Sewing'), ('washing', 'Washing'), ('finishing', 'Finishing'), ('packing', 'Packing')], max_length=50)),
                ('rejected_quantity', models.PositiveIntegerField()),
                ('defect_details', models.TextField()),
                ('corrective_action', models.TextField(blank=True)),
                ('reported_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.defectcategory')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reports', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Rejection Report',
                'verbose_name_plural': 'Rejection Reports',
            },
        ),
    ]
