# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defectcategory',
            options={'ordering': ['-id'], 'verbose_name': 'DefectCategory', 'verbose_name_plural': 'DefectCategorys'},
        ),
        migrations.AlterModelOptions(
            name='endlineqc',
            options={'ordering': ['-id'], 'verbose_name': 'EndLineQC', 'verbose_name_plural': 'EndLineQCs'},
        ),
        migrations.AlterModelOptions(
            name='fabricinspection',
            options={'ordering': ['-id'], 'verbose_name': 'FabricInspection', 'verbose_name_plural': 'FabricInspections'},
        ),
        migrations.AlterModelOptions(
            name='finalinspection',
            options={'ordering': ['-id'], 'verbose_name': 'FinalInspection', 'verbose_name_plural': 'FinalInspections'},
        ),
        migrations.AlterModelOptions(
            name='inlineqc',
            options={'ordering': ['-id'], 'verbose_name': 'InlineQC', 'verbose_name_plural': 'InlineQCs'},
        ),
        migrations.AlterModelOptions(
            name='rejectionreport',
            options={'ordering': ['-id'], 'verbose_name': 'RejectionReport', 'verbose_name_plural': 'RejectionReports'},
        ),
    ]
