# Generated by Django 5.2.13 on 2026-08-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['-id'], 'verbose_name': 'RolePermission', 'verbose_name_plural': 'RolePermissions'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-id'], 'verbose_name': 'UserRole', 'verbose_name_plural': 'UserRoles'},
        ),
        migrations.AddField(
            model_name='permission',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Optional: filter permission to a specific model (e.g. buyers.Buyer). If null, permission applies globally to the model type.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbac_permissions', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='permission',
            name='object_id',
            field=models.CharField(blank=True, help_text='Optional: filter permission to a specific object instance ID. Used together with content_type for per-object access.', max_length=255, null=True),
        ),
    ]
