# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('merchandising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=100)),
                ('capacity_per_day', models.PositiveIntegerField()),
                ('booking_date', models.DateField()),
                ('allocated_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('in_use', 'In Use'), ('released', 'Released')], default='allocated', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_bookings', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Capacity Booking',
                'verbose_name_plural': 'Capacity Bookings',
            },
        ),
        migrations.CreateModel(
            name='LinePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=100)),
                ('plan_date', models.DateField()),
                ('target_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed')], default='planned', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_plans', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Line Plan',
                'verbose_name_plural': 'Line Plans',
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('daily_target', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='merchandising.purchaseorder')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Production Plan',
                'verbose_name_plural': 'Production Plans',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('likelihood', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('closed', 'Closed')], default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
            },
        ),
        migrations.CreateModel(
            name='StyleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('cost', 'Cost Analysis'), ('feasibility', 'Feasibility Study'), ('market', 'Market Analysis'), ('production', 'Production Analysis')], max_length=50)),
                ('findings', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('analyzed_by', models.CharField(max_length=255)),
                ('analysis_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='merchandising.style')),
            ],
            options={
                'verbose_name': 'Style Analysis',
                'verbose_name_plural': 'Style Analyses',
            },
        ),
    ]
