# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ie_planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitybooking',
            options={'ordering': ['-id'], 'verbose_name': 'CapacityBooking', 'verbose_name_plural': 'CapacityBookings'},
        ),
        migrations.AlterModelOptions(
            name='lineplan',
            options={'ordering': ['-id'], 'verbose_name': 'LinePlan', 'verbose_name_plural': 'LinePlans'},
        ),
        migrations.AlterModelOptions(
            name='productionplan',
            options={'ordering': ['-id'], 'verbose_name': 'ProductionPlan', 'verbose_name_plural': 'ProductionPlans'},
        ),
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'ordering': ['-id'], 'verbose_name': 'RiskAssessment', 'verbose_name_plural': 'RiskAssessments'},
        ),
        migrations.AlterModelOptions(
            name='styleanalysis',
            options={'ordering': ['-id'], 'verbose_name': 'StyleAnalysis', 'verbose_name_plural': 'StyleAnalysis'},
        ),
    ]
