# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmnotification',
            options={'ordering': ['-id'], 'verbose_name': 'AlarmNotification', 'verbose_name_plural': 'AlarmNotifications'},
        ),
        migrations.AlterModelOptions(
            name='joborder',
            options={'ordering': ['-id'], 'verbose_name': 'JobOrder', 'verbose_name_plural': 'JobOrders'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-id'], 'verbose_name': 'Timeline', 'verbose_name_plural': 'Timelines'},
        ),
    ]
