# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('supplier_type', models.CharField(choices=[('fabric', 'Fabric Supplier'), ('accessory', 'Accessory Supplier'), ('trim', 'Trim Supplier'), ('general', 'General Supplier')], default='general', max_length=50)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='QuotationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_terms', models.CharField(blank=True, max_length=255)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('validity_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('negotiating', 'Negotiating')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Quotation Analysis',
                'verbose_name_plural': 'Quotation Analyses',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('fabric', 'Fabric'), ('accessory', 'Accessory'), ('trim', 'Trim')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('required_date', models.DateField()),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('requested_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raw Material Requisition',
                'verbose_name_plural': 'Raw Material Requisitions',
                'unique_together': {('requisition_number',)},
            },
        ),
        migrations.CreateModel(
            name='RawMaterialBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('item_type', models.CharField(choices=[('fabric', 'Fabric'), ('accessory', 'Accessory'), ('trim', 'Trim')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partial_received', 'Partially Received'), ('received', 'Fully Received'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Raw Material Booking',
                'verbose_name_plural': 'Raw Material Bookings',
                'unique_together': {('booking_number',)},
            },
        ),
    ]
