# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationanalysis',
            options={'ordering': ['-id'], 'verbose_name': 'QuotationAnalysis', 'verbose_name_plural': 'QuotationAnalysis'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialbooking',
            options={'ordering': ['-id'], 'verbose_name': 'RawMaterialBooking', 'verbose_name_plural': 'RawMaterialBookings'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialrequisition',
            options={'ordering': ['-id'], 'verbose_name': 'RawMaterialRequisition', 'verbose_name_plural': 'RawMaterialRequisitions'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-id'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
