# Generated by Django 6.0.7 on 2026-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofexchange',
            options={'ordering': ['-id'], 'verbose_name': 'BillOfExchange', 'verbose_name_plural': 'BillOfExchanges'},
        ),
        migrations.AlterModelOptions(
            name='disbursement',
            options={'ordering': ['-id'], 'verbose_name': 'Disbursement', 'verbose_name_plural': 'Disbursements'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='letterofcredit',
            options={'ordering': ['-id'], 'verbose_name': 'LetterOfCredit', 'verbose_name_plural': 'LetterOfCredits'},
        ),
        migrations.AlterModelOptions(
            name='realization',
            options={'ordering': ['-id'], 'verbose_name': 'Realization', 'verbose_name_plural': 'Realizations'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-id'], 'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='sodfctransfer',
            options={'ordering': ['-id'], 'verbose_name': 'SODFCTransfer', 'verbose_name_plural': 'SODFCTransfers'},
        ),
        migrations.AlterModelOptions(
            name='supplierdocument',
            options={'ordering': ['-id'], 'verbose_name': 'SupplierDocument', 'verbose_name_plural': 'SupplierDocuments'},
        ),
    ]
